### ISSUE TITLE
GameRuleLogic methods should be public

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/backend#301]
They are now private, but they should be usable by the pupils and this breaks the GUI project which also uses `validateShape` and `validateSetMove`.

**Comment by anarchuser** [comment]
Which methods exactly?
I tried to make those methods private that don't make sense to use outside.
`validateSetMove` should be replaced with `isValidSetMove` which returns a `Boolean` instead of throwing up.

`validateShape` is implicitly checked in `validateSetMove`; does it make sense to have separately or do we rather want something like `getValidShapes`?
